# Generated by Django 5.0.1 on 2024-01-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('taxa_cambio', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
