# Generated by Django 5.0.1 on 2024-01-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversao', '0002_remove_moeda_codigo_remove_moeda_taxa_cambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moeda',
            name='cotacao',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
